- hosts: localhost
  tasks:
    - name: Create a windows web app with non-exist app service plan
      azure_rm_webapp:
        subscription_id: da9510b8-3397-4012-a20c-328a1b93c19e
        resource_group: devopscle
        name: WinWebapp
        plan:
          resource_group: devopscle
          name: winAppServicePlan
          is_linux: false
          sku: S1
